### ISSUE TITLE
No documentation available

### ISSUE THREAD

**Issue by rokafeller** [martinschaef/roomba#1]
Hi,
the web page you point to for additional information is dead [http://cs.gmu.edu/%7Ezduric/cs101/pmwiki.php/Main/APITutorial](url).
Would you have a copy of that content or anything that might facilitate the use of this useful library?

thanks

**Comment by martinschaef** [comment]
Unfortunately not... I actually just googled that link.

**Comment by KTibow** [comment]
Wayback machine, anybody? [http://web.archive.org/web/20160827153405/http://cs.gmu.edu/~zduric/cs101/pmwiki.php/Main/APITutorial](http://web.archive.org/web/20160827153405/http://cs.gmu.edu/~zduric/cs101/pmwiki.php/Main/APITutorial)
